name: Continuous Delivery

on:
  pull_request:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery - Gerando artefato
        uses: actions/upload-artifact@v4
        with:
          name: projeto-calculadora
          path: |
            **.py
            README.md

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - name: Baixando artefato gerado
        uses: actions/download-artifact@v4
        with:
          name: projeto-calculadora

      - name: Exibindo arquivos recebidos
        run: ls -R

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login no DockerHub (se quiser usar)
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: user/app:latest
